### ISSUE TITLE
Can't connect to Home Assistant that doesn't require a port for REST

### ISSUE THREAD

**Issue by dumbstart** [Mawalu/node-homeassistant#5]
My HA setup is external facing but doesn't require a port to be able to send and receive through the REST api. I wanted to try yours out and was having some problems and since I'm very new to Node I wanted to see if I was on the right course.

**Comment by mawalu** [comment]
I don't think I fully understand your problem. The Home Assistant Frontend, REST API and websocket API all use the same port, if you can reach the web interface you should be able to reach the websocket endpoint.
